/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pck_View;

import Pck_Control.ClienteControl;
import Pck_DAO.ClienteDAO;
import Pck_Model.ClienteModel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedro
 */
public class ClienteView extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoView
     */
    public ClienteView() {
        initComponents();
        carregarTabelaClientes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        lblAdicionarCliente = new javax.swing.JLabel();
        jScrollTblCliente = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < tblCliente.getColumnCount(); i++) {
            tblCliente.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        btnApagar = new javax.swing.JToggleButton();
        btnAdicionar = new javax.swing.JToggleButton();
        btnVoltar = new javax.swing.JToggleButton();
        lblItemTabela = new javax.swing.JLabel();
        lblItemTabela1 = new javax.swing.JLabel();
        lblItemTabela2 = new javax.swing.JLabel();
        lblItemTabela3 = new javax.swing.JLabel();
        lblItemTabela4 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBackground(Color.WHITE);            // Fundo branco
        btnCancelar.setForeground(Color.BLACK);            // Cor do texto (pode ser branco se quiser invisível)
        btnCancelar.setBorderPainted(false);               // Remove borda
        btnCancelar.setFocusPainted(false);                // Remove destaque de foco
        btnCancelar.setContentAreaFilled(false);           // Remove preenchimento padrão
        btnCancelar.setOpaque(true);  // Necessário para aplicar o fundo
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 42, 53));

        lblAdicionarCliente.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblAdicionarCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblAdicionarCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAdicionarCliente.setText("Clientes");
        lblAdicionarCliente.setToolTipText("");

        jScrollTblCliente.setColumnHeaderView(null);

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        // Estilo geral da tabela
        tblCliente.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        tblCliente.setRowHeight(30);
        tblCliente.setShowGrid(false);
        tblCliente.setIntercellSpacing(new Dimension(0, 0));
        tblCliente.setSelectionBackground(new Color(0x55, 0x51, 0x4A));
        tblCliente.setSelectionForeground(Color.WHITE);

        tblCliente.setTableHeader(null);
        jScrollTblCliente.setViewportView(tblCliente);

        btnApagar.setBackground(new java.awt.Color(255, 51, 51));
        btnApagar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnApagar.setForeground(new java.awt.Color(255, 255, 255));
        btnApagar.setText("Apagar");
        btnApagar.setBorderPainted(false);               // Remove borda
        btnApagar.setFocusPainted(false);                // Remove destaque de foco
        btnApagar.setContentAreaFilled(false);           // Remove preenchimento padrão
        btnApagar.setOpaque(true);  // Necessário para aplicar o fundo
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnAdicionar.setBackground(new java.awt.Color(51, 153, 255));
        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setBorderPainted(false);               // Remove borda
        btnAdicionar.setFocusPainted(false);                // Remove destaque de foco
        btnAdicionar.setContentAreaFilled(false);           // Remove preenchimento padrão
        btnAdicionar.setOpaque(true);  // Necessário para aplicar o fundo
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setBackground(Color.WHITE);            // Fundo branco
        btnVoltar.setForeground(Color.BLACK);            // Cor do texto (pode ser branco se quiser invisível)
        btnVoltar.setBorderPainted(false);               // Remove borda
        btnVoltar.setFocusPainted(false);                // Remove destaque de foco
        btnVoltar.setContentAreaFilled(false);           // Remove preenchimento padrão
        btnVoltar.setOpaque(true);  // Necessário para aplicar o fundo
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblItemTabela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemTabela.setForeground(new java.awt.Color(255, 255, 255));
        lblItemTabela.setText("CPF");

        lblItemTabela1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemTabela1.setForeground(new java.awt.Color(255, 255, 255));
        lblItemTabela1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItemTabela1.setText("Nome Completo");

        lblItemTabela2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemTabela2.setForeground(new java.awt.Color(255, 255, 255));
        lblItemTabela2.setText("Endereço");

        lblItemTabela3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemTabela3.setForeground(new java.awt.Color(255, 255, 255));
        lblItemTabela3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItemTabela3.setText("Telefone");

        lblItemTabela4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemTabela4.setForeground(new java.awt.Color(255, 255, 255));
        lblItemTabela4.setText("Crédito");

        btnAlterar.setBackground(new java.awt.Color(40, 42, 53));
        btnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        //btnConsultar.setBorderPainted(false);               // Remove borda
        btnAlterar.setFocusPainted(false);                // Remove destaque de foco
        btnAlterar.setContentAreaFilled(false);           // Remove preenchimento padrão
        btnAlterar.setOpaque(true);  // Necessário para aplicar o fundo
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lblItemTabela)
                .addGap(132, 132, 132)
                .addComponent(lblItemTabela1)
                .addGap(114, 114, 114)
                .addComponent(lblItemTabela2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(lblItemTabela3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblItemTabela4)
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollTblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblAdicionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblAdicionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemTabela)
                    .addComponent(lblItemTabela1)
                    .addComponent(lblItemTabela2)
                    .addComponent(lblItemTabela3)
                    .addComponent(lblItemTabela4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollTblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        this.setVisible(false);
        new CadastrarClienteView().setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        new MenuView().setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.setVisible(false);
        new MenuView().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JToggleButton btnApagar;
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollTblCliente;
    private javax.swing.JLabel lblAdicionarCliente;
    private javax.swing.JLabel lblItemTabela;
    private javax.swing.JLabel lblItemTabela1;
    private javax.swing.JLabel lblItemTabela2;
    private javax.swing.JLabel lblItemTabela3;
    private javax.swing.JLabel lblItemTabela4;
    private javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables

    private void carregarTabelaClientes() {

        try {
            ClienteDAO clienteDAO = new ClienteDAO();
            List<ClienteModel> listaClientes = clienteDAO.listarClientes(); // método que você deve implementar

            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("CPF");
            modelo.addColumn("Nome");
            modelo.addColumn("Endereço");
            modelo.addColumn("Telefone");
            modelo.addColumn("Crédito");

            for (ClienteModel cliente : listaClientes) {
                modelo.addRow(new Object[]{
                    cliente.getA01_cpf(),
                    cliente.getA01_nome(),
                    cliente.getA01_endereco(),
                    cliente.getA01_telefone(),
                    cliente.getA01_credito()
                });
            }

            tblCliente.setModel(modelo);
            tblCliente.setDefaultEditor(Object.class, null);

            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

            for (int i = 0; i < tblCliente.getColumnCount(); i++) {
                tblCliente.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
